### ISSUE TITLE
what is the difference to other diff libraries?

### ISSUE THREAD

**Issue by Vad1mo** [simasch/beandiff#1]
What is different in beandiff then in those libs?
1. [javers](http://javers.org/)
2. [java-object-diff](https://github.com/SQiShER/java-object-diff)
3. [java-diff-utils](https://code.google.com/p/java-diff-utils/)

**Comment by simasch** [comment]
beandiff compares two objects based on the attribute names using reflection.
The two objects don't need to be of the same class.
